# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dockerized

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pythondemos.azurecr.io/tweeter3:latest'
  PYTHON_VERSION: '3.7'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.pipelines.txt
    pip install pytest pytest-azurepipelines
    pip install -e .
  displayName: 'Install dependencies'
- script: |
    python -m pytest tests/
  displayName: 'pytest'
- script: docker login pythondemos.azurecr.io -u pythondemos -p $DOCKER_LOGIN_PASSWORD
  env:
    DOCKER_LOGIN_PASSWORD: $(acrkey)
  displayName: 'docker login'
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
- script: docker push $(imageName)
  displayName: 'docker push'
