version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ..:/workspace
    command: sleep infinity
    environment:
      DJANGO_SETTINGS_MODULE: tweeter3.settings.devcontainer

  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: LocalPassword