version: '3'

services:
  app:
    image: tweeterapp
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ..:/workspace
    command: sleep infinity
    environment:
      DJANGO_SETTINGS_MODULE: tweeter3.settings.devcontainer
  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: IAmAPassword1!